#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# utils
delayed() {
	sleep $1
	eval "$2"
}

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd &					# music player daemon-you might prefer it as a service though
# remaps &				# run the remaps script, switching caps/esc and more; check it for more info
setbg &					# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
# xcompmgr &				# xcompmgr for transparency #(compositor)
picom & #--experimental-backends --backend glx --xrender-sync-fence & #(compositor)
dunst &					# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &				# Remove mouse when idle

delayed "1m" "dropbox" & # start dropbox 1m after
delayed "2m" "pkill -RTMIN+20 dwmblocks" & # refresh coins

# xsetroot -cursor_name left_ptr
